export const userRole = {
  ADMIN: 'ADMIN',
  STUDENT: 'STUDENT',
  CHAIRMAN: 'CHAIRMAN',
  SUPER_ADMIN: 'SUPER_ADMIN',
  HALL_OPERATOR: 'HALL_OPERATOR',
  DEPARTMENT_OPERATOR: 'DEPARTMENT_OPERATOR'
} as const;
